apiVersion: v1
kind: Service
metadata:
  labels:
    app: akka-bootstrap-demo
  name: "integration-test-kubernetes-dns"
spec:
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: "akka-bootstrap-demo"
  type: LoadBalancer